### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by laamalif** [tytkal/python-hijiri-ummalqura#7]
Date: 10 Safar 1004 Hijri to Gregorian

```
um = HijriDate(1004,2,10)
print um.year_gr
```

Error:

```
Traceback (most recent call last):
  File "hj.py", line 21, in <module>
    um = HijriDate(1004,2,12)
  File "/usr/local/lib/python2.7/dist-packages/umalqurra/hijri_date.py", line 35, in __init__
    self.set_date(year,month,day)
  File "/usr/local/lib/python2.7/dist-packages/umalqurra/hijri_date.py", line 53, in set_date
    self.year_gr, self.month_gr, self.day_gr = um.hijri_to_gregorian(year,month,day)
  File "/usr/local/lib/python2.7/dist-packages/umalqurra/hijri.py", line 49, in hijri_to_gregorian
    mcjdn = id + UmalqurraArray.ummalqura_dat[i - 1] - 1
IndexError: list index out of range

```

**Comment by tytkal** [comment]
I think we need to put validation where we validate date there is min and max for dates

**Comment by sigmaSd** [comment]
This is respectively the minimal and maximal accepted date I found `1356,1,1` `1500,12,30` .
Plus I noticed there is no constraints on the day input , for example something like 
`HijriDate(1400,1,1000)` is valid input.
